### ISSUE TITLE
[Feature Request] Google doc for story submissions

### ISSUE THREAD

**Issue by ldahleen54** [TheGreatAxios/thebetterbecauseproject#27]
The current process of story submissions is a bit complicated for contributors. 

We need to come up with a way for the users to both click a button to submit to a google doc

We would also like it to not be required to have a google account.
We also need to explain the guidelines for contributions before the contributor is sent to the google doc.

We are waiting on revised submission guidelines but if you have potential UI suggestions for how to achieve this comment on this post.

**Comment by jcolborn-dropdeadgames** [comment]
When looking at this from the UI and the server-side I think there are a few things we can do.

We can present a modal that lists the submission guidelines to the user entering the story. This can just be an overlay and they can click out. They could also have to click a button before moving on to writing a document.

As for the actual document, from research, I cannot find a way to draft a document without a Google account. One thing we could do is create an on-page editor that would allow the user to write the document or upload an already created document. We could then use the Google Docs API to write this to a Google Drive that could be accessed by the editor. It depends on how the editing process would go. There is the possibility of using the Google Docs API to push and pull data for the story directly on the page. I would think somewhere there would need to be an account, though. 

The Google Docs API reference can be found here: https://developers.google.com/docs/api/reference/rest
