### ISSUE TITLE
[Feature Request] Categorize stories 

### ISSUE THREAD

**Issue by ldahleen54** [TheGreatAxios/thebetterbecauseproject#30]
More details will be added soon

**Comment by erlendtp1996** [comment]
Were you thinking about adding something like for users to tag their stories, then allow users to filter by them on the stories page?

**Comment by TheBetterBecauseLady** [comment]
I was thinking that one of the story editors would read through each story and note which categories specific stories would fall under. Here's the current filter/categorization system:

https://docs.google.com/document/d/1jZmCC43z55XKw4NhENTVFwYvwUwsXaX3Sx9tJNVdMfQ/edit?usp=sharing
